package com.sppcco.helperlibrary.dialog.material_dialog;

/**
 * Created by m_pejam on 01/31/18.
 *
 */

public enum DialogType {
  WARNING_AGREE_DISAGREE,
  WARNING_AGREE_DISMISS,
  WARNING_APPROVE_DISAGREE,
  WARNING_APPROVE_DISMISS,
  WARNING_YES_NO,
  ERROR_AGREE_DISAGREE,
  ERROR_AGREE_DISMISS,
  ERROR_APPROVE_DISAGREE,
  ERROR_APPROVE_DISMISS,
  ERROR_YES_NO,
  WARNING_APPROVE,
  ERROR_SAVE_DELETE,
  ERROR_SAVE_DISMISS,
  ERROR_DELETE_DISMISS,
  WARNING_SAVE_DELETE,
  WARNING_SAVE_DISMISS,
  WARNING_DELETE_DISMISS,
  ERROR_EDIT_DISMISS,
  WARNING_EDIT_DISMISS,
  WARNING,
}
